name: Pull Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - image.yml

jobs:
  pull-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read YAML
        id: image
        run: |
          REPO=$(python -c "import yaml;print(yaml.safe_load(open('image.yml'))['image']['repository'])")
          TAG=$(python -c "import yaml;print(yaml.safe_load(open('image.yml'))['image']['tag'])")
          
          echo "repo=$REPO" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Pull Docker image
        run: |
          docker pull ${{ steps.image.outputs.repo }}:${{ steps.image.outputs.tag }}